### ISSUE TITLE
Improve the database schema for consulta_academica

### ISSUE THREAD

**Issue by danibritods** [danibritods/consulta_academica#1]
The goal of this issue is to improve the database schema for `consulta_academica`, which is an abstracted copy of the Academico production database. The goal of the abstraction is to make  future analysis and features using data more efficient, flexible and simpler to implement. 

Currently `consulta_academica` only copies the minimal tables required for the `demanda_academica` feature. This feature is the counting of the number os students demanding each subject from the university. The rationale is to use this features to build the MVP of the consulta_academica. 

## Tasks
- [x] Identify the tables and columns that need to be abstracted or transformed in consulta_academica
- [x] Design a new schema for consulta_academica that reflects the abstraction and transformation logic
- [x] Test the new schema and verify that it works as expected
- [ ] Document the new schema and the rationale behind it
